***Numpy***

In [2]:
## numpy array
# np.array
import numpy as np

a = np.array([1 , 2, 3])
print(a)

[1 2 3]


In [3]:
# 2D and 3D array
b = np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
# this is a tenser

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [9]:
# np.arange # works as range functions
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# with reshape
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [14]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# np.random
np.random.random((3,4))

array([[0.38485062, 0.41506757, 0.97380414, 0.83071694],
       [0.87653956, 0.11628193, 0.9162074 , 0.44113548],
       [0.57589321, 0.87482374, 0.98766937, 0.27477225]])

In [19]:
# np.linspace
np.linspace(-10,10,10,dtype=int)
# genetates points between the ranges in equal distance

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [18]:
# np.identity
np.identity(3) # diagonals are 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attribute

In [21]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(1,9).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# ndim --> no of dimensions
a3.ndim

3

In [27]:
# shape
a3.shape
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# size --> no of elements
a3.size

8

In [29]:
# itemsize --> size in memory
a1.itemsize

8

In [30]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [32]:
# astype --> changing datatype
a3.dtype
a3.astype(np.int32)
# previously it was 64bits and now it is 32bits

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

Array Operations

In [34]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [35]:
## scalar operations

# arithmetic
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [37]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
## vector operations
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions

In [44]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

print(a1)

[[16. 89. 34.]
 [ 9. 58. 77.]
 [73. 13. 55.]]


In [47]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1)
np.max(a1,axis=1) # to find max in each row

array([89., 77., 73.])

In [49]:
# mean/median/std/var
np.var(a1,axis=1)

array([964.22222222, 820.66666667, 632.        ])

In [50]:
# trigonometric functions
np.sin(a1)

array([[-0.28790332,  0.86006941,  0.52908269],
       [ 0.41211849,  0.99287265,  0.99952016],
       [-0.67677196,  0.42016704, -0.99975517]])

In [52]:
# dot product --> 2 matrix (3,4) and (4,3)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [53]:
# log and exponent
np.exp(a1)

array([[8.88611052e+06, 4.48961282e+38, 5.83461743e+14],
       [8.10308393e+03, 1.54553894e+25, 2.75851345e+33],
       [5.05239363e+31, 4.42413392e+05, 7.69478527e+23]])

In [54]:
# round/floor/cell
np.round(np.random.random((2,3))*100)

array([[44., 52., 34.],
       [34., 67., 68.]])

*Indexing and Slicing*



In [55]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
print(a2)
# to locate 6 in a2 array
a2[1,2] # [row,colomn]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6

In [60]:
print(a3)
# to locate 5 in a3 (3d array--tenser)
a3[1,0,1] # [matrix,row,colomn]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


5

In [ ]:
## slicing

In [61]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a1[2:5] # 2 to 5

array([2, 3, 4])

In [63]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
# for 1st row in 2d
a2[0,:] # ':' means all columns

array([0, 1, 2, 3])

In [66]:
# 3rd column
a2[:,2] # ':' means all rows

array([ 2,  6, 10])

In [67]:
# for 5,6,9,10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [69]:
# for 0,3,8,11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [70]:
# for 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [72]:
# for 4 and 7
a2[1,0::3]

array([4, 7])

In [77]:
# for 1,2,3,5,6,7
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:
## 3d array
a3 = np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
print(a3[0,1]) # for 1 matrix middle row
print(a3[1,:,1]) # for 2 matrix middle column
print(a3[2,1:,1:]) # for 22,23,25,26

[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]


In [91]:
# for 0,2,18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

*Iterating*

In [93]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [95]:
for i in a1 :
  print(i)

0
1
2
3
4
5
6
7
8
9


In [96]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [97]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [98]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


*Reshape*

In [99]:
# reshape -- already done

In [100]:
# Transpose ---row into column and vicevarsa
np.transpose(a2)
a2.T # also can be return like this

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [102]:
# ravel -- converts all into 1D array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [103]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

*Stacking*

In [105]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [107]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [108]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

*Spliting*

In [109]:
# horizonal spliting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [112]:
# vertical spliting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]