***Numpy Assignment***

1. What is a Python library? Why do we use Python libraries?

2. What is the difference between Numpy array and List?

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
# First import the numpy
import numpy as np

print(np.array(a)) # printing the array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# Shape
np.shape(a)

(3, 4)

In [13]:
# size
np.size(a)

12

In [11]:
# Dimensions
np.ndim(a)

2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [40]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# converting into numpy array
b = np.array(a)

b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
## first row of the array
b[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [42]:
a =[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# converting into numpy array
c = np.array(a)

c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
# the element at the third row and fourth column
c[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [44]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# converting into numpy array
d = np.array(a)

d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
# odd elements in the array are 2,4,6,8,10,12
# by slicing 
d[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [68]:
# generating a numpy array of random 3*3 matrix with value between 0 to 1
np.random.random(9).reshape(3,3)

array([[0.57997329, 0.68284845, 0.9322991 ],
       [0.24506528, 0.13649409, 0.89661506],
       [0.56821795, 0.78662658, 0.54447817]])

8. Describe the difference between np.random.rand and np.random.randn?


In [75]:
# numpy.random.rand example

np.random.rand(9).reshape(3,3)

array([[0.18426188, 0.25703676, 0.40143718],
       [0.67284436, 0.78734396, 0.1025062 ],
       [0.55736296, 0.04055506, 0.98496892]])

In [76]:
# numpy.random.randn example

np.random.randn(9).reshape(3,3)

array([[-0.32765892,  0.81868691,  0.67157512],
       [ 1.02442255,  0.40312031, -0.43544389],
       [ 1.61469715, -1.16181636,  1.65811812]])

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [82]:

a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# Converting into numpy array
e = np.array(a)

e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
# increasing the dimension of the array
np.expand_dims(e,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [86]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# Converting into numpy array
f = np.array(a)

In [87]:
# Transpose ---row into column and vicevarsa
np.transpose(f)


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [88]:
f.T # also can be return like this

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:

1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrices
4. Subtract matrix B from A
5. Divide Matrix B by A

In [92]:
## Converting matrix into Numpy Matrix

A2 = [[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]]

B2 = [[1, 2, 3, 4], 
      [5, 6, 7, 8],
      [9, 10, 11, 12]]

A3 = np.array(A2)
B3 = np.array(B2)

In [93]:
## 1. Index wise Multiplication 

# using "prod"
print(np.prod(A3))
print(np.prod(B3))

479001600
479001600


In [95]:
## 2. Matrix multiplication

''' cannot perform multipication because the shape of the matrix is suitable 
    shapes of the matrix must be in (3,4) and (4,3) but here the shape is 
    (3,4) and (3,4).
'''

' cannot perform multipication because the shape of the matrix is suitable \n    shapes of the matrix must be in (3,4) and (4,3) but here the shape is \n    (3,4) and (3,4).\n'

In [99]:
## 3. Add both the matrices

add = np.add(A3,B3)
add

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [102]:
## 4. Subtract matrix B from A

sub = np.subtract(A3,B3)
sub

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [104]:
## 5. Divide Matrix B by A

div = np.divide(B3,A3)

div

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?


13.  What is the significance of the np.linalg.inv function?


14. What does the np.reshape function do, and how is it used?


15. What is broadcasting in Numpy?


In [105]:
## Example------->

# create 1-D array
array1 = np.array([1, 2, 3])

# create 2-D array
array2 = np.array([[1], [2], [3]])

# add arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
